### ISSUE TITLE
sudo splatoon-painter my_picture.bmp运行后，switch 打开手柄匹配界面经过长时间无反应。

### ISSUE THREAD

**Issue by RickyWonggh** [yaoshiu/Splatoon-Painter#2]
:~/Splatoon-Painter$ sudo splatoon-painter my_picture.bmp 
/usr/local/bin/splatoon-painter:92: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by yaoshiu** [comment]
请确保在系统中打开了蓝牙且未与switch配对，如已配对过使用`-r`参数或尝试在系统蓝牙设置中移除Nintendo Switch
